name: Deploy to Heroku
on: 
  push:
    tags: 
      -'v*' #anything that starts with V will trigger this
      -'v*-alpha' #anything that starts with v except alpha
jobs:
deploy_to_heroku:
  runs-on: ubuntu-latest
  steps: 
  - name: Checkout src
    uses: actions/checkout@v2
  - name: Deploy
    uses: akhileshns/heroku-deploy@v3.12.12
    with:
      heroku_api_key: ${{ secrets.heroku_api_key }}
      heroku_app_name: dovebear
      heroku_email: ${{secrets.email }} #hide email
      branch: ${{github.ref_name }} #deploy to specific branch